## configuration for the desmos - see https://DOME-Marketplace.github.io/access-node for configuration documentation
access-node:
  desmos:
    # -- should the desmos-blockchain-connector be enabled
    enabled: true
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    fullnameOverride: desmos
    image:
      repository: in2workspace/in2-desmos-api
      # Overrides the image tag whose default is the chart appVersion.
      tag: v1.0.2
      pullPolicy: Always
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - host: access-node.operator-marketplace.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - access-node.operator-marketplace.com
          secretName: access-node-tls-secret
    ## deployment specific configuration
    app:
      ## profile (test == dev)
      profile: dev
      ## debug level
      logLevel: INFO
      ## information about the access-node operator
      operator:
        # -- DID of the operator in the format **did:elsi:VAT{VAT_NUMBER}**. VAT_NUMBER: The VAT indetification number of the operator
        # -- Example: did:elsi:VATES-TEST6037254
        organizationIdentifier: did:elsi:VATES-TEST6037254
      ## connection information for the context broker
      broker:
        paths:
          entities: "/ngsi-ld/v1/entities"
          entityOperations: "/ngsi-ld/v1/entityOperations"
          subscriptions: "/ngsi-ld/v1/subscriptions"
          temporal: "/ngsi-ld/v1/temporal/entities"

        # -- provider of the broker
        provider: scorpio
        # -- internal address of the context broker to be used by the connector
        internalDomain: http://scorpio:9090
        # -- external address of the broker. Will be included in the hashlink and used by other access-nodes to retrieve the actual entities
        externalDomain: http://scorpio:9090
      ## configuration of ngsi-ld entities to listen for
      ngsiSubscription:
        # -- a list of entity-types the connector is interested in
        entityTypes: catalog,product-offering,category,individual,organization,product,service-specification,product-offering-price,resource-specification,product-specification
      ## configuration to connect to the dlt-adapter
      dltAdapter:
        # -- provider of the dlt-adapter component
        provider: digitelts
        # -- (local) address of the dlt-adapter
        internalDomain: http://dlt-adapter:8080
        # -- (external) address of the dlt-adapter
        externalDomain: http://dlt-adapter:8080
        ## configuration of subscriptions at the blockchain
      txSubscription:
        # -- a list of entity-types the connector is interested in
        entityTypes: catalog,product-offering,category,individual,organization,product,service-specification,product-offering-price,resource-specification,product-specification
      # -- URL of the Marketplace of the operator
      externalDomain: "https://operator-marketplace.com"
      externalAccessNodesUrls:
        enableCustomUrls: false
        customUrls: ""
      # -- Private key of the operator to sign JWT. Alternatively, you can add it as a sealed secret.
      # -- To generate use https://dome-marketplace.github.io/dome-crypto-generator/. Use the value of Desmos Keys -> Private Key
      privateKey: 
        value: "0x15aa33a07f6680d1bb3e7524ea3f6ce6ba0eb39a3efa146c3d84a0487505d9f8"
        existingSecret:
          # -- should an existing secret be used
          enabled: false
          # -- name of the secret
          name: desmos-secret
          # -- key to retrieve the password from
          key: private-key
    ## configuration of the database to be used by the blockchain-connector
    db:
      # -- host of the db
      host: desmos-postgres
      # -- port of the host of the db
      port: 5432
      # -- should be true if is an external service
      externalService: false
      # -- name of the db
      name: desmos
      # -- username to be used
      username: postgres
      # -- password to be used
      password: postgres
      # -- existing secret to retrieve the db password
      existingSecret:
        # -- should an existing secret be used
        enabled: false
        # -- name of the secret
        name: desmos-secret
        # -- key to retrieve the password from
        key: desmos-db-password

  ## configuration for the dlt-adapter - see https://DOME-Marketplace.github.io/access-node/dlt-adapter for configuration documentation
  dlt-adapter:
    # -- should the dlt-adapter be enabled
    enabled: true
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    fullnameOverride: dlt-adapter
    # -- Environment variables to be set for the dlt-adapter
    # -- Private key of the operator in the Alastria Red-T Blockchain to sign transactions as a sealed secret.
    existingSecret:
      enabled: false
      name: access-node-secret
      key: private-key
    env:
      DEBUG: "*"
      # -- Private key of the operator in the Alastria Red-T Blockchain to sign transactions. Alternatively, you can add it as a sealed secret.
      # -- To generate use https://dome-marketplace.github.io/dome-crypto-generator/. Use the value of DLT Keys -> Private Key
      PRIVATE_KEY: "0x426fcbb2bebdc7607638db9879d21a18d0585ff3ec007f23dc8776e9a1c07904"
      RPC_ADDRESS: "https://red-t.alastria.io/v0/9461d9f4292b41230527d57ee90652a6"
      # -- To generate use https://dome-marketplace.github.io/dome-crypto-generator/. Use the value of DLT Keys -> ISS
      ISS: "0xb34dcb3fcccc37d89a4742617eef81d0920cbd2e0204ceea2bb3ddd1f8b85876"
    
  ## configuration of postgres to be used for the blockchain-connector - see https://github.com/bitnami/charts/tree/main/bitnami/postgresql for details
  postgresql:
    # -- should the postgresql deployment be enabled
    enabled: true
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    fullnameOverride: desmos-postgres
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    nameOverride: desmos-postgres
    ## auth configuration for the database
    auth:
      # -- username to be used
      username: postgres
      # -- password to be used
      password: postgres
      # -- should the default postgres user be enabled
      enablePostgresUser: true
      # -- existing secret
      #existingSecret: access-node-secret
      #secretKeys:
      #  adminPasswordKey: desmos-db-password
      #  userPasswordKey: desmos-db-password
    ## configuration of the postgres primary replica
    primary:
      ## provide db initialization
      initdb:
        ## provide scripts for initialization
        scripts:
          # -- create the database as expected by the blockchain-connector
          create.sh: |
            psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE desmos;"  

  ## configuration of the context-broker - see https://github.com/FIWARE/helm-charts/tree/main/charts/scorpio-broker-aaio for details
  scorpio:
    # -- should scorpio be enabled
    enabled: true
    ## configuration of the image to be used
    image:
      # -- repository to be used - resource friendly all-in-one-runner without kafka
      repository: scorpiobroker/all-in-one-runner
      # -- tag of the image to be used - latest java image without kafka
      tag: java-4.1.11
    ## configuration of the database to be used by broker
    db:
      # -- host of the db
      dbhost: scorpio-postgis
      # -- username to be used
      user: postgres
      # -- password to be used
      password: postgres
      existingSecret:
        # -- should an existing secret be used
        enabled: false
        # -- name of the secret
        name: access-node-secret
        # -- key to retrieve the password from
        key: scorpio-db-password
    ## configuration of the readiness probe
    readinessProbe:
      # -- path to be used for the readiness probe, older versions used /actuator/health
      path: /q/health
    ## configuration of the liveness probe
    livenessProbe:
      # -- path to be used for the readiness probe, older versions used /actuator/health
      path: /q/health
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    fullnameOverride: scorpio
    ## configuration to be used for the service offered by scorpio
    service:
      # -- ClusterIP is the recommended type for most clusters
      type: ClusterIP

  ## configuration for kafka in case its used by scorpio - see https://github.com/bitnami/charts/tree/main/bitnami/kafka
  kafka:
    # -- should kafka be enabled?
    enabled: false

  ## configuration of postgis to be used for scorpio - see https://github.com/bitnami/charts/tree/main/bitnami/postgresql for details
  postgis:
    # -- should postgis be enabled
    enabled: true
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    fullnameOverride: scorpio-postgis
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    nameOverride: scorpio-postgis
    ## auth configuration for the database
    auth:
      # -- username to be used
      username: postgres
      # -- should the default postgres user be enabled
      enablePostgresUser: true
      # -- password to be used
      password: postgres
      # -- existing secret
      #existingSecret: access-node-secret
      #secretKeys:
      #  adminPasswordKey: scorpio-db-password
      #  userPasswordKey: scorpio-db-password
    ## configuration of the postgres primary replicas
    primary:
      ## provide db initialization
      initdb:
        ## provide scripts for initialization
        scripts:
          # -- enable the postgis extension and create the database as expected by scorpio
          enable.sh: |
            psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE EXTENSION postgis;"
            psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE ngb;"

  ## configuration of the tm-forum-api - see https://github.com/FIWARE/helm-charts/tree/main/charts/tm-forum-api for details
  tm-forum-api:
    fullnameOverride: tm-forum-api
    nameOverride: tm-forum-api
    # -- should tm-forum-api be enabled
    enabled: true
    ## configuration to be used by every api-deployment if nothing specific is provided.
    defaultConfig:
      # -- configuration to be used for the image of the containers
      image:
        # -- current latest tag
        tag: "0.26.2"
      # -- ngsi-ld broker connection information
      ngsiLd:
        # -- address of the broker
        url: http://scorpio:9090
      # -- default context to be used when contacting the context broker
      contextUrl: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      # -- host that the tm-forum api can be reached at, when the proxy is enabled it should be set to that address. If not, set the host for each api individually
      serverHost: http://localhost:8080
    ## configuration for the api proxy, to serve all apis through one kubernetes service
    apiProxy:
      # -- the proxy must be enabled
      enabled: true
    apis:
    - name: party-catalog
      image: tmforum-party-catalog
      basePath: /

    - name: customer-bill-management
      image: tmforum-customer-bill-management
      basePath: /

    - name: customer-management
      image: tmforum-customer-management
      basePath: /

    - name: product-catalog
      image: tmforum-product-catalog
      basePath: /

    - name: product-inventory
      image: tmforum-product-inventory
      basePath: /

    - name: product-ordering-management
      image: tmforum-product-ordering-management
      basePath: /

    - name: resource-catalog
      image: tmforum-resource-catalog
      basePath: /

    - name: resource-function-activation
      image: tmforum-resource-function-activation
      basePath: /

    - name: resource-inventory
      image: tmforum-resource-inventory
      basePath: /

    - name: service-catalog
      image: tmforum-service-catalog
      basePath: /

    - name: account
      image: tmforum-account
      basePath: /

    - name: agreement
      image: tmforum-agreement
      basePath: /

    - name: usage-management
      image: tmforum-usage-management
      basePath: /
