## configuration of the context-broker - see https://github.com/FIWARE/helm-charts/tree/main/charts/scorpio-broker-aaio for details
scorpio:
  # -- should scorpio be enabled
  enabled: true
  ## configuration of the database to be used by broker
  db:
    # -- host of the db
    dbhost: postgis
    # -- username to be used
    user: postgres
    # -- password to be used
    password: postgres
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  fullnameOverride: scorpio

## configuration for kafka in case its used by scorpio - see https://github.com/bitnami/charts/tree/main/bitnami/kafka
kafka:
  # -- should kafka be enabled? 
  enabled: false

## configuration of postgis to be used for scorpio - see https://github.com/bitnami/charts/tree/main/bitnami/postgresql for details
postgis:
  # -- should postgis be enabled
  enabled: true
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  fullnameOverride: postgis
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  nameOverride: postgis
  ## auth configuration for the database
  auth:
    # -- username to be used
    username: postgres
    # -- should the default postgres user be enabled
    enablePostgresUser: true
    # -- username to be used
    password: postgres

## configuration of the tm-forum-api - see https://github.com/FIWARE/helm-charts/tree/main/charts/tm-forum-api for details
tm-forum-api:
  # -- should tm-forum-api be enabled
  enabled: true
  ## configuration to be used by every api-deployment if nothing specific is provided.
  defaultConfig:
    # --  ngsi-ld broker connection information
    ngsiLd:
      # -- address of the broker
      url: http://scorpio:9090
    # -- default context to be used when contacting the context broker
    contextUrl: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
  ## configuration for the api proxy, to serve all apis through one kubernetes service 
  apiProxy:
    # -- should the proxy be enabled
    enabled: true

## configuration for the desmos - see https://DOME-Marketplace.github.io/access-node for configuration documentation
access-node.desmos:
  # -- should the desmos-blockchain-connector be enabled
  enabled: true
  ## deployment specific configuration
  app:
    ## profile (dev == sbx)
    profile: dev
    ## information about the access-node operator
    operator:
      # -- did of the organization running the node
      organizationIdentifier: did:elsi:VATES-S9999999E
    ## connection information for the context broker
    broker:
      # -- external address of the broker. Will be included in the hashlink and used by other access-nodes to retrieve the actual entities
      externalDomain: http://scorpio:9090
      ## configuration of the database to be used by the blockchain-connector
    db:
      # -- password to be used
      password: postgres
      # -- username to be used
      username: postgres

## configuration for the dlt-adapter - see https://DOME-Marketplace.github.io/access-node/dlt-adapter for configuration documentation
access-node.dlt-adapter:
  # -- should the dlt-adapter be enabled
  enabled: true
  env:
    PRIVATE_KEY: "0xe2afef2c880b138d741995ba56936e389b0b5dd2943e21e4363cc70d81c89346"
    RPC_ADDRESS: "https://red-t.alastria.io/v0/9461d9f4292b41230527d57ee90652a6"
    ISS: "0x43b27fef24cfe8a0b797ed8a36de2884f9963c0c2a0da640e3ec7ad6cd0c493d"

## configuration of postgres to be used for the blockchain-connector - see https://github.com/bitnami/charts/tree/main/bitnami/postgresql for details
access-node.postgresql:
  # -- should the postgresql deployment be enabled
  enabled: true
  ## auth configuration for the database
  auth:
    # -- username to be used
    username: postgres
    # -- password to be used
    password: postgres